// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADgh-CeHnymaecrANI98OwGKfrhfSknuk',
    appId: '1:578726705768:web:e76876244ae19d1bb4d9dd',
    messagingSenderId: '578726705768',
    projectId: 'securityreport-c509f',
    authDomain: 'securityreport-c509f.firebaseapp.com',
    storageBucket: 'securityreport-c509f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB11NnE-clOYkPA1SsUEubxZ3iROCokl50',
    appId: '1:578726705768:android:c42e7bd0f1f8b28fb4d9dd',
    messagingSenderId: '578726705768',
    projectId: 'securityreport-c509f',
    storageBucket: 'securityreport-c509f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqrXYQX2Fr5e4edHuTVEskvj8gTkij_0',
    appId: '1:578726705768:ios:4401a4651b808284b4d9dd',
    messagingSenderId: '578726705768',
    projectId: 'securityreport-c509f',
    storageBucket: 'securityreport-c509f.appspot.com',
    iosBundleId: 'com.example.nothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARqrXYQX2Fr5e4edHuTVEskvj8gTkij_0',
    appId: '1:578726705768:ios:4401a4651b808284b4d9dd',
    messagingSenderId: '578726705768',
    projectId: 'securityreport-c509f',
    storageBucket: 'securityreport-c509f.appspot.com',
    iosBundleId: 'com.example.nothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADgh-CeHnymaecrANI98OwGKfrhfSknuk',
    appId: '1:578726705768:web:5624ee1a1f06038ab4d9dd',
    messagingSenderId: '578726705768',
    projectId: 'securityreport-c509f',
    authDomain: 'securityreport-c509f.firebaseapp.com',
    storageBucket: 'securityreport-c509f.appspot.com',
  );

}